sample_shape: [96, 96, 96]
spacing: [1.5, 1.5, 2]
norm_intensity: false
a_min: -175
a_max: 250
rotate_p: 0.1
flip_p: 0.1
scale_p: 0
shift_p: 0.5
backbone: swt
vit_patch_shape: [2, 2, 2]
base_feature_size: 48
layer_channels: [48, 96, 192, 384]
num_heads: [3, 6, 12, 24]
vit_depths: [2, 2, 6, 2]
swin_window_size: [6, 6, 6]
decoder: conv
num_post_upsampling_layers: 1
train_batch_size: 1
num_crop_samples: 4
learning_rate: 2e-4
weight_decay: 1e-5
num_train_epochs: 3000
warmup_epochs: 100
num_seg_heads: 1
crop: pn
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
