sample_shape: [96, 96, 96]
spacing: [1.5, 1.5, 2]
norm_intensity: false
a_min: -175
a_max: 250
rotate_p: 0.1
flip_p: 0.1
scale_p: 0
shift_p: 0.5
backbone: swin
layer_channels: [24, 48, 96, 192, 384]
num_heads: [1, 3, 6, 12, 24]
layer_depths: [1, 2, 2, 6, 2]
kernel_sizes: [3, 6, 6, 6, 6]
decoder: conv
num_seg_heads: 1
train_batch_size: 1
num_crop_samples: 4
learning_rate: 2e-4
weight_decay: 1e-5
num_train_epochs: 5000
warmup_epochs: 100
crop: pn
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
