num_folds: 5
#sample_slices: 192
#sample_size: 192
sample_shape: [192, 192, 48]
spacing: [0.75781244, 0.75781244, 3]
norm_intensity: false
a_min: -175
a_max: 250
scale_p: 0.1
shift_p: 0.1
backbone: swin
num_conv_layers: 2
layer_channels: [24, 48, 96, 192, 384, 768]
num_heads: [1, 1, 3, 6, 12, 24]
layer_depths: [1, 2, 2, 2, 6, 2]
kernel_sizes: [3, 3, 6, 6, 6, 6]
decoder: conv
num_seg_heads: 3
train_batch_size: 2
num_crop_samples: 2
learning_rate: 1e-2
weight_decay: 1e-5
num_train_epochs: 5000
warmup_epochs: 0
optimizer_set_to_none: true
crop: pn
crop_pos: 3
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
