sample_shape: [192, 192, 48]
spacing: [0.75781244, 0.75781244, 3]
norm_intensity: true
a_min: null
a_max: null
norm_mean: null
norm_std: null
rotate_p: 0.5
flip_p: 0.5
scale_p: 0.1
shift_p: 0
backbone: swin
stem_stride: 1
stem_kernel: 3
num_conv_layers: 1
conv_norm: instance
conv_act: leakyrelu
layer_channels: [24, 48, 96, 192, 384, 768]
num_heads: [-1, -1, 3, 6, 12, 24]
layer_depths: [1, 1, 2, 2, 6, 2]
kernel_sizes: [3, 3, 6, 6, 6, 6]
conv_in_channels: null
drop_path_rate: 0
decoder: conv
num_post_upsamplings: 0
num_seg_heads: 3
train_batch_size: 2
optim: AdamW
learning_rate: 2e-4
weight_decay: 1e-2
num_train_epochs: 3000
warmup_epochs: 100
crop: pn
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
