sample_size: 96
sample_slices: 96
base_feature_size: 48
vit_depths: [2, 2, 6, 2]
vit_num_heads: [3, 6, 12, 24]
vit_patch_shape: [2, 2, 2]
swin_window_size: [6, 6, 6]
mask_block_shape: [16, 16, 16]
mask_ratio: 0.85
visible_factor: 0.1
train_batch_size: 4
learning_rate: 2e-4
weight_decay: 1e-5
max_steps: 60000
warmup_steps: 1000
spacing: [1.5, 1.5, 2]
norm_intensity: false
norm_pix_loss: false
a_min: -175
a_max: 250
flip_p: 0.5
rotate_p: 0.5
scale_p: 0
shift_p: 0
mask_value: dist
loss: l2
