sample_size: 192
sample_slices: 192
base_feature_size: 48
vit_depths: [2, 2, 2, 6, 2]
vit_num_heads: [2, 3, 6, 12, 24]
vit_patch_shape: [2, 2, 2]
swin_window_size: [6, 6, 6]
mask_block_shape: [16, 16, 16]
mask_ratio: 0.8
visible_factor: 0.1
train_batch_size: 2
learning_rate: 1e-4
weight_decay: 1e-5
max_steps: 100000
spacing: [1, 1, 2]
norm_intensity: false
norm_pix_loss: false
a_min: -175
a_max: 250
scale_p: 0
shift_p: 0
mask_value: param
loss: l2
