sample_size: 192
sample_slices: 192
base_feature_size: 24
vit_depths: [2, 2, 2, 4, 2]
vit_num_heads: [3, 3, 6, 12, 24]
vit_patch_shape: [2, 2, 2]
swin_window_size: [6, 6, 6]
mask_block_shape: [16, 16, 16]
mask_ratio: 0.8
non_mask_factor: 0.1
train_batch_size: 4
learning_rate: 1e-4
weight_decay: 1e-5
max_steps: 100000
spacing: [1.5, 1.5, 2]
norm_intensity: false
norm_pix_loss: false
a_min: -175
a_max: 250
scale_p: 0
shift_p: 0
mask_value: uniform
