_base:
  - ../_base/aug/dummy-2D.yaml
  - backbone: ../_base/backbone/swin6-l032.yaml
    optimizer: ../_base/optimizer/adamw.yaml
    scheduler: ../_base/scheduler/cosine-warmup50.yaml

optimizer:
  lr: 2.5e-4

num_input_channels: 1
train_batch_size: 16
spacing: [0.75, 0.75, 3]
sample_shape: [192, 192, 48]
norm_intensity: true
gradient_clip_val: 1
gradient_clip_algorithm: norm

dummy_dim: 2
rotate_p: 0.35
scale_p: 0.35
scale_range: [0.6, 1.5]
simulate_low_res_p: 0.15

decoder:
  name: snim-decoder
  kwargs:
    layer_channels: [96, 192, 384, 384]
mask_patch_size: [4, 4, 1]  # physically isotropic
norm_pix_loss: false  # patch size is too small
dis_loss_factor: 1

num_epoch_batches: 100
save_every_n_epochs: 10
log_every_n_steps: 10
