num_folds: 5
sample_size: 192
sample_slices: 192
encoder: swt
base_feature_size: 24
vit_depths: [2, 2, 2, 6, 2]
vit_num_heads: [2, 3, 6, 12, 24]
vit_patch_shape: [2, 2, 2]
swin_window_size: [6, 6, 6]
decoder: sunetr
train_batch_size: 2
num_crop_samples: 1
learning_rate: 1e-4
weight_decay: 1e-5
num_train_epochs: 3000
warmup_epochs: 50
num_seg_heads: 3
spacing: [1, 1, 3]
norm_intensity: false
a_min: -175
a_max: 250
scale_p: 0.1
shift_p: 0.1
optimizer_set_to_none: true
crop: cls
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
