num_folds: 5
sample_size: 192
sample_slices: 192
encoder: swt
base_feature_size: 48
vit_depths: [2, 2, 2, 6]
vit_num_heads: [2, 4, 8, 16]
vit_patch_shape: [2, 2, 2]
swin_window_size: [8, 8, 8]
decoder: sunetr
train_batch_size: 2
num_crop_samples: 1
learning_rate: 1e-4
weight_decay: 1e-5
num_train_epochs: 5000
num_seg_heads: 3
spacing: [1, 1, 3]
norm_intensity: false
a_min: -175
a_max: 250
scale_p: 0.1
shift_p: 0.1
optimizer_set_to_none: true
crop: cls
squared_dice: false
include_background: true
dice_nr: 1e-5
dice_dr: 1e-5
